<a href="https://colab.research.google.com/github/sthabijay/kritrim-buddhi/blob/main/Pytorching.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip list

Package                          Version
-------------------------------- -------------------
absl-py                          1.4.0
accelerate                       0.34.2
aiohappyeyeballs                 2.4.0
aiohttp                          3.10.5
aiosignal                        1.3.1
alabaster                        0.7.16
albucore                         0.0.16
albumentations                   1.4.15
altair                           4.2.2
annotated-types                  0.7.0
anyio                            3.7.1
argon2-cffi                      23.1.0
argon2-cffi-bindings             21.2.0
array_record                     0.5.1
arviz                            0.19.0
astropy                          6.1.3
astropy-iers-data                0.2024.9.16.0.32.21
astunparse                       1.6.3
async-timeout                    4.0.3
atpublic                         4.1.0
attrs                            24.2.0
audioread                        3.0.1
autograd                 

In [2]:
import torch

In [3]:
test = torch.randn(2,4,3)
print(test)

tensor([[[-0.8702, -0.1773,  1.1341],
         [-0.9194,  0.0846, -1.2660],
         [-0.7441,  1.7550, -0.8365],
         [-0.4789, -0.3323,  1.3300]],

        [[-0.8096, -0.2757,  0.1081],
         [ 0.2981,  0.8511,  0.7809],
         [-0.5374, -1.2000, -0.6052],
         [ 0.0035,  1.3861,  1.8505]]])


In [4]:
tensor0 = torch.arange(12)
print(tensor0)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [5]:
tensor0 = tensor0.reshape(3,-1)
tensor0

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [6]:
tensor1 = tensor0[:, 1:3]
tensor1

tensor([[ 1,  2],
        [ 5,  6],
        [ 9, 10]])

In [7]:
list1 = [1,2,3,4,5,6]
list1[1:3]

[2, 3]

In [8]:
tensorA = torch.tensor([1,2,3])
tensorB = torch.tensor([4,5,6])

tensorA.add_(tensorB)

tensorA

tensor([5, 7, 9])

In [9]:
import torch.nn as nn
import torch.nn.functional as F

In [14]:
class Model(nn.Module):
  def __init__(self, input=4, h1=8, h2=16, output=3):
    super().__init__()
    self.fc1 = nn.Linear(input, h1)
    self.fc2 = nn.Linear(h1, h2)
    self.out = nn.Linear(h2, output)

  def forward(self, x):
    x = F.relu(self.fc1(x))
    x = F.relu(self.fc2(x))
    x = self.out(x)

    return x

In [15]:
torch.manual_seed(41)
model = Model()

In [18]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [24]:
url = 'https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv'
my_df = pd.read_csv(url)
my_df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [26]:
my_df['species'] = my_df['species'].replace('setosa', 0.0)
my_df['species'] = my_df['species'].replace('versicolor', 1.0)
my_df['species'] = my_df['species'].replace('virginica', 2.0)
my_df

sepal_length  sepal_width  petal_length  petal_width  species
0             5.1          3.5           1.4          0.2      0.0
1             4.9          3.0           1.4          0.2      0.0
2             4.7          3.2           1.3          0.2      0.0
3             4.6          3.1           1.5          0.2      0.0
4             5.0          3.6           1.4          0.2      0.0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3      2.0
146           6.3          2.5           5.0          1.9      2.0
147           6.5          3.0           5.2          2.0      2.0
148           6.2          3.4           5.4          2.3      2.0
149           5.9          3.0           5.1          1.8      2.0

[150 rows x 5 columns]

In [27]:
X = my_df.drop('species', axis=1)
y = my_df['species']

X = X.values
y= y.values

In [30]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=41)